name: Build release package

on:
  release:
    types:
      - published

jobs:
  build-release-package:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin repository
        uses: actions/checkout@v2
        with:
          path: wp-content/plugins/ll-voordemensen/
          fetch-depth: 1
      - name: Generate zip file
        run: |
          cd wp-content/plugins/
          zip -r ll-voordemensen-${{ github.event.release.tag_name }}.zip ll-voordemensen
      - name: Upload zip to release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./wp-content/plugins/ll-voordemensen-${{ github.event.release.tag_name }}.zip
          asset_name: ll-voordemensen-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
