name: Build release package

on:
  release:
    types:
      - published

jobs:
  build-release-package:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin repository
        uses: actions/checkout@v4
        with:
          path: wp-content/plugins/ll-voordemensen/
          fetch-depth: 1
      - name: Upload zip to release assets
        id: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: ll-voordemensen-${{ github.event.release.tag_name }}.zip
          path: /home/runner/work/ll-voordemensen/ll-voordemensen/wp-content/plugins/ll-voordemensen/
